name: DEPLOY

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.3.1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install node packages
        run: yarn

      - name: deploy
        run: | 
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global url.https://${{ secrets.PAT }}@github.com/.insteadOf https://github.com/
          yarn deploy-gh-prefix-paths